apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-claim
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-claim
  resources:
    requests:
      storage: 4Gi